image: node:7.5.0

stages:
  - test
  - build
  - deploy

build:
  type: build
  script:
  - npm install --only=dev
  - npm install style-loader node-sass css-loader
  - npm run webpack:build


test:
  type: test
  script:
  - apt-get update -qy
  - npm install
  - npm install --only=dev
  - node app.js


deploy:
  type: deploy
  image: ruby:2.3.3
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get update
  - gem install dpl
  - dpl --provider=heroku --skip_cleanup=true --app=hackdoddles --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
